synthetic-package: false
arb-dir: lib/l18n
template-arb-file: app_en.arb
preferred-supported-locales: [fa]
untranslated-messages-file: untranslatedText.txt
output-localization-file: app_localizations.dart
